apiVersion: v1
kind: ConfigMap
metadata:
  name: pangolin-config
data:
  config.yml: |
    # To see all available options, please visit the docs:
    # https://docs.fossorial.io/Pangolin/Configuration/config

    app:
      dashboard_url: "https://{{ .Values.pangolin.dashboard_url }}"
      log_level: "info"
      save_logs: false

    domains:
      domain1:
        base_domain: "{{ .Values.pangolin.base_domain }}"
        cert_resolver: "letsencrypt"

    server:
      external_port: 3000
      internal_port: 3001
      next_port: 3002
      internal_hostname: "pangolin"
      session_cookie_name: "p_session_token"
      resource_access_token_param: "p_token"
      resource_access_token_headers:
        id: "P-Access-Token-Id"
        token: "P-Access-Token"
      resource_session_request_param: "p_session_request"
      secret: {{ .Values.pangolin.secret }}
      cors:
        origins: ["https://{{ .Values.pangolin.dashboard_url }}"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

    traefik:
      cert_resolver: "letsencrypt"
      http_entrypoint: "web"
      https_entrypoint: "websecure"

    gerbil:
      start_port: 51820
      base_endpoint: "{{ .Values.pangolin.base_domain }}"
      use_subdomain: false
      block_size: 24
      site_block_size: 30
      subnet_group: 100.89.137.0/20

    rate_limits:
      global:
        window_minutes: 1
        max_requests: 500

    users:
      server_admin:
        email: "{{ .Values.pangolin.server_admin.email }}"
        password: "{{ .Values.pangolin.server_admin.password }}"

    flags:
      require_email_verification: false
      disable_signup_without_invite: true
      disable_user_create_org: true
      allow_raw_resources: true
      allow_base_domain_resources: true

    # postgres:
    #   connection_string: postgresql://pangolin:password@cluster-rw.postgres.svc.cluster.local:5432/pangolin?sslmode=disable
